 post {{baseUrl}}/createUser
 content-type: application/json

 {
    "username": "test",
    "password": "test"
 }

###

# @name login
post {{baseUrl}}/login
 content-type: application/json

 {
    "username": "test",
    "password": "test"
 }

 ###

 @authToken = {{login.response.headers.X-AuthToken}}



get {{baseUrl}}/sampleAuthenticatedEndpoint
content-type: application/json
authorization: Bearer {{authToken}}